# Generated by Django 4.2.2 on 2023-08-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrecord',
            name='image',
        ),
    ]
