# Generated by Django 4.2.2 on 2023-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_remove_predictionrecord_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
