# Generated by Django 4.2.2 on 2023-09-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_predictionrecord_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='localization',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
